### ISSUE TITLE
Clarification: difference and similarity to Group-Object

### ISSUE THREAD

**Issue by thorstenkampe** [cdhunt/PSelect#1]
Can you give some information regarding the difference and similarity between PSelect and PowerShell's `Group-Object`?

**Comment by cdhunt** [comment]
If you pipe `Get-Process` to `Group-Object Name` you get results that include `Count`, `Name` and `Group` where `Group` is just a collection of `Process` objects. If you want to more information about the contents of those collections, you have to pipe the `Group` into one or more commands.

If you want to aggregate some values from properties within that `Group` of `Process` objects, `PSelect` makes that easier. It also includes some functionality to help make the output human readable: column title naming; Format string support; and sorting.

```powershell
Get-Process | PSelect {
    Field ProcessName
    Field WorkingSet -as Count -Count
    Field WorkingSet -Sum
    Field Handles -as OpenHandles -StdDev
    
    GroupBy ProcessName

    SortData
}
```

Output:
```
ProcessName                    Count WorkingSet      OpenHandles
-----------                    ----- ----------      -----------
1Password.NativeMessagingHost      1   12873728              NaN
AgileBits.OnePassword.Desktop      1   92909568              NaN
ApplicationFrameHost               1   30789632              NaN
audiodg                            1   24076288              NaN
chrome                            22 2114838528 684.092328456338
cmd                                1    2789376              NaN
com.docker.localhost-forwarder     1    8134656              NaN
com.docker.proxy                   1    9719808              NaN
com.docker.service                 1   68952064              NaN
conhost                           10   60030976 12.3630273171438
csrss                              2   10903552 95.4594154601839
                              ...
```

To do that with just `Group-Object` would take several loops. Under the hood, `PSelect` is actually just doing that for you based on the `Field` parameters you supply. A key difference is PSelect returns only the data you ask for and the raw data is discarded whereas `Group-Object` will passthru all of the data unless you use the `-NoElement` switch.
