### ISSUE TITLE
Problem transforming Group-Object to PSelect

### ISSUE THREAD

**Issue by thorstenkampe** [cdhunt/PSelect#3]
I've got some example code. The code reads a file with about 300,000 words - one per line - and groups the words by length. The grouped output is sorted by count:
```
$file    = 'F:\cygwin\home\thorsten\python\Wordlist.txt'
$content = Get-Content -Path $file -ReadCount 0
```
```
$content | Group-Object -Property Length | Sort-Object -Property Count
```
This is the output:
```
Count Name                      Group
----- ----                      -----
    5 24                        {formaldehydesulphoxylate, pathologicopsychological, scientificophilosophical, tetraiodophenolphthalein...}
   17 23                        {anthropomorphologically, blepharosphincterectomy, epididymodeferentectomy, formaldehydesulphoxylic...}
   31 1                         {*, 0, 1, 2...}
[...]
43555 8                         {!@#$%^&*, 0racl38i, 0racl39i, 0racle10...}
46919 10                        {abalienate, abaptiston, abasedness, abbagliamo...}
48228 9                         {0racle10i, 123456789, 199220706, <invalid>...}
```
The PSelect code I came up with looks like this
```
$content | PSelect {
               Field -Name Length -As Count -Count
               Field -Name Length

               GroupBy -Name Length

               SortData
           } 
```
The output looks like this:
```
Count Length
----- ------
   31 1
46919 10
26902 11
[...]
34384 7
43555 8
48228 9
```
Now my questions and observations:
1. the `Group-Object` code takes about 10 seconds to run. `PSelect` takes 4:17min to run. That's about 25 times longer.
2. Is it possible to sort the output on the `Count` column and not the `Length` column?
3. The `Length` column is obviously sorted alphabetically and not numerically. This looks like a bug.
4. Is it possible to add the "raw data" (the `Group` column from `Group-Object`)?

**Comment by cdhunt** [comment]
1. That's expected. PSelect does a lot more work than `Group-Object` and if all you do is `-Count` you're doing a lot more work to produce similar results as `Group-Object`.
2. Currently, it just sorts based on the `GroupBy` field.
3. Your input is a string so the output is strings. You'd have to transform the input data for PowerShell and PSelect to treat `Length` as integers. PSelect can format other types to `string`, but not `string` to `int`.
4. No. If you just need the functionality of `Group-Object` just use that. PSelect was developed for aggregating multiple properties in multiple ways. i.e. https://github.com/cdhunt/PSelect#example---fromcsv
